### ISSUE TITLE
Unlist packages with date version

### ISSUE THREAD

**Issue by diegofrata** [connelhooley/AkkaTestingHelpers#1]
On NuGet the package 2018.3.6.2 keeps showing up as the most up to date, but 2.0.0 is the actual latest. You should probably unlist all packages using the yyyy.M.d format so it will stop nagging people to update! :)

**Comment by connelhooley** [comment]
I thought I'd done that! Thanks for the heads up I'll do that now.

**Comment by connelhooley** [comment]
According to NuGet.org version 2 is the latest version:
https://www.nuget.org/packages/ConnelHooley.AkkaTestingHelpers/

Also according to NuGet.org the version you're referring to, is already marked as de-listed:
https://www.nuget.org/packages/ConnelHooley.AkkaTestingHelpers/2018.3.6.2

I don't know too much about NuGet but some suggestions:
- Do any of your projects in the solution still reference the older version? I think if that's the case it still comes up in search results until you remove it.
- Could you try reinstalling the NuGet package in all of your projects in the solution and see if that helps?
- This is unlikely, but are you mirroring NuGet at all? I've worked in companies that use products such as Artifactory which is an on-prem copy of the NuGet feed so they host packages inside their internal network. If you're doing that you might want to make sure the mirror is up to date. I think I uploaded version 2 then later on de-listed the date packages so its possible the snapshot was taken in between?

**Comment by diegofrata** [comment]
@connelhooley apologies! I should have double checked. Indeed we use a mirror and I think the mirror is not coping very well with the package being delisted.
