### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by diegofrata** [connelhooley/AkkaTestingHelpers#2]
I noticed this library didn't get updated in quite a long time. Are there any plans for any work on this? I am asking just out of curiosity. It does work pretty well even with more recent versions of Akka and I have been using it in a few of my projects.

**Comment by connelhooley** [comment]
Hi @diegofrata, glad you're finding the helpers useful. I'll probably do an updated NuGet package that targets standard 2.0 and Akka 1.4 soon, but apart from that I have no plans for any future enhancements at present.

**Comment by connelhooley** [comment]
I updated the package a while back to use Akka 1.4 and .NET Standard 2.0 but forgot to update this ticket. Closing it now but feel free to open another ticket if you have any feature requests, for the most part I think this package does what I aimed to do when I created it though.
