### ISSUE TITLE
TellMessageAndWaitForException doesn't work

### ISSUE THREAD

**Issue by charlesfayal** [connelhooley/AkkaTestingHelpers#4]
I have debugged through my tests, I see where the Actor under test in the framework is throwing the exception, but the TellMessageAndWaitForException times out.

**Comment by connelhooley** [comment]
Can you provide an example that replicates the issue please?

Below is an example of how the feature works if it helps:

https://github.com/connelhooley/AkkaTestingHelpers/blob/master/AkkaTestingHelpers.MediumTests/UnitTestFrameworkTests/Examples/Example6_UnhandledExceptions.cs
